import rtconfig
Import('RTT_ROOT')
from building import *

src_drv = ['console.c']
src_bsp = ['application.c', 'startup.c', 'board.c']

src	= File(src_bsp + src_drv)
CPPPATH = [RTT_ROOT + '/bsp/dm365']
group = DefineGroup('Startup', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
